apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-projet-drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mon-projet-drupal
  template:
    metadata:
      labels:
        app: mon-projet-drupal
    spec:
      containers:
        - name: mon-projet-drupal
          image: REGISTRE_DOCKER/mon_projet_drupal:latest
          ports:
            - containerPort: 80
          env:
            # Définir ici les variables d'environnement spécifiques à votre projet Drupal
            - name: DB_HOST
              value: "localhost"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: ""
